disqusShortname = "bplociennik"
googleAnalytics = "UA-173395383-1"
baseURL = "https://bplociennik.com/"
title = "Bartosz Płóciennik"
languageCode = "en"
theme = "soho"
paginate = 5
builtWith = true

DefaultContentLanguage = "pl"

[languages]
  [languages.pl]
    weight = 1
    languageName = "Polski"
    languageCode = "pl"
    contentDir = "content/polish"
    titleDescription = "python, django, programowanie, technologie, dobre praktyki"

enableInlineShortcodes = true
summarylength = 10
enableEmoji = true

[params]
author = "Bartosz Płóciennik"
profilePicture = "static/profile.webp"
copyright = "Bartosz Płóciennik"
themeColor = "#2d6682"

## Set as many as you want.
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/bartosz-plociennik/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/bplociennik"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/bplociennik_"

[menu]
  # === Polish ===
  [[languages.pl.menu.main]]
  name = "Strona główna"
  weight = 100
  identifier = "home"
  url = "/"

  [[languages.pl.menu.main]]
  name = "Posty"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[languages.pl.menu.main]]
  name = "Kategorie"
  weight = 300
  identifier = "categories"
  url = "/categories/"

  [[languages.pl.menu.main]]
  name = "Tagi"
  weight = 400
  identifier = "tags"
  url = "/tags/"

  [[languages.pl.menu.main]]
  name = "O mnie"
  identifier = "about"
  weight = 500
  url = "/about/"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup]
  [markup.profilePicture]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4
