baseURL = "https://bplociennik.com/"
languageCode = "en-us"
defaultContentLanguage = "en"

author = "Bartosz Płóciennik"
title = "Bartosz Płóciennik"
theme = "hugo-vitae-3"
paginate = 10
enableRobotsTXT = true
enableEmoji = true

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-173395383-1"
copyright = "© Copyright notice | [Vitae](https://github.com/dataCobra/hugo-vitae) theme for [Hugo](https://gohugo.io)"

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"


[params]
	# Use homepage.md instead of a list of posts
	homepage = false

	# Add meta keywords in head part (Site Keywords or Tags of Page)
	keywords = ["python","django","fastapi","web development"]

	# Add meta description in head part
	description = "bplociennik.com | just my personal blog mostly for myself"

	# Add pagetitle to homepage <title> tag
	pagetitle = "bplociennik.com | python web development, fastapi, django and more"

	# Add a subtitle to your website
	subtitle = "<code>> hi there! _</code>"

	# Add math typesetting with KaTeX (Global with this Param)
	math = true

	# Optional 80x80 avatar image.
	avatar = "static/profile.webp"

	# Optional favicons for website
	#favicon = true

	# Add list of sections that should show up on the homepage
        mainSections = ["post"]

	# Add list of Sections/Types that should no be considered by RSS
	#nofeedSections = ["post"]

	# Deactivate Taxonomies for specific page types
	#disableTaxoTypes = [""]

	# Custom CSS applied to default styles. (Path could be "static/css/")
	#customCSS = "css/custom.css"


# Navigation
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 5

# Social Menu
[[params.social]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/bplociennik"

[[params.social]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/bartosz-plociennik/"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "/index.xml"


# Comments
[params.comments]
enabled = true

# Comment provider:
engine = "disqus"

# Content types to disable comments on.
disableOnTypes = ["page"]

[params.comments.disqus]
shortname = "bplociennik"


#[markup]
#  [markup.profilePicture]
#  codeFences = true
#  guessSyntax = false
#  hl_Lines = ""
#  lineNoStart = 1
#  lineNos = false
#  lineNumbersInTable = true
#  noClasses = true
#  style = "monokai"
#  tabWidth = 4

#enableInlineShortcodes = true
#summarylength = 10
